spring:
  application:
    name: client-discovery
server:
  port: 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - "/info"
  endpoint:
    info:
      enabled: true
    beans:
      enabled: true
